<?php

namespace Core\Driver;

use Core\Entity\Form;
/**
 * Description class for the database driver
 * @author Sébastien JOLY
 * @author Jonathan SANTONI
 */
abstract class FormDriver {

	/**
	 * Ask the type of a given column
	 * @param String $name	: The name of the column
	 * @return array 		: An array with the result of the request
	 */
	public abstract function getFieldType($name);
	
	/**
	 * Change the form used by the driver
	 * @param Form $form 	: An instance of Form
	 */
	public abstract function setForm($form);
	
	/**
	 * Get the form used by the driver
	 * @return form 		: An instance of Form
	 */
	public abstract function getForm();
	
	/**
	 * Ask if the column is index of table
	 * @param String $name 	: The name of the column to test
	 * @return boolean 		: True if is index else false  
	 */
	public abstract function isIndex($name);
	
	/**
	 * Ask if the column is autogenerated
	 * @param String $name 	: The name of the column to test
	 * @return boolean 		: True if is index else false  
	 */
	public abstract function isAutoGenerated($name);
}